services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=gestion_emprendedores.settings
    volumes:
      # 👉 si no necesitas persistencia de la base de datos, comenta esta línea
      # - ./db.sqlite3:/app/db.sqlite3
    healthcheck:
      test: ["CMD-SHELL","python - <<'PY'\nimport urllib.request, sys\n\ntry:\n    urllib.request.urlopen('http://localhost:8000/health', timeout=3)\nexcept Exception:\n    sys.exit(1)\nPY"]
      interval: 30s
      timeout: 5s
      retries: 5
