services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=gestion_emprendedores.settings
    # Si no usas volúmenes, NO pongas 'volumes:' vacío.
    # healthcheck opcional:
    healthcheck:
      test: ["CMD-SHELL","python - <<'PY'\nimport urllib.request, sys\n\ntry:\n    urllib.request.urlopen('http://localhost:8000/health', timeout=3)\nexcept Exception:\n    sys.exit(1)\nPY"]
      interval: 30s
      timeout: 5s
      retries: 5
